#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           7.0.0-build.57+g2cc4f0c931
//       
//       Command:
//           LottieGen -Language Cppwinrt -Namespace MU_XC_NAMESPACE -InputFile Controls_01_Checkmark.json
//       
//       Input file:
//           Controls_01_Checkmark.json (10205 bytes created 11:08-08:00 Nov 18 2020)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "common.h"
#include "Controls_01_Checkmark.g.h"

    // Name:        Controls_01_Checkmark
    // Frame rate:  60 fps
    // Frame count: 70
    // Duration:    1166.7 mS
    // ___________________________________________________________________________________
    // |        Marker         |        Constant         | Frame |   mS   |   Progress   |
    // |_______________________|_________________________|_______|________|______________|
    // | NormalToHover_Start   | M_NormalToHover_Start   |   0.0 |    0.0 | 0.0F         |
    // | NormalToHover_End     | M_NormalToHover_End     |   9.0 |  150.0 | 0.128571436F |
    // | NormalToPressed_Start | M_NormalToPressed_Start |  10.0 |  166.7 | 0.142857149F |
    // | NormalToPressed_End   | M_NormalToPressed_End   |  19.0 |  316.7 | 0.271428585F |
    // | HoverToNormal_Start   | M_HoverToNormal_Start   |  20.0 |  333.3 | 0.285714298F |
    // | HoverToNormal_End     | M_HoverToNormal_End     |  29.0 |  483.3 | 0.414285719F |
    // | HoverToPressed_Start  | M_HoverToPressed_Start  |  30.0 |  500.0 | 0.428571433F |
    // | HoverToPressed_End    | M_HoverToPressed_End    |  39.0 |  650.0 | 0.557142854F |
    // | PressedToNormal_Start | M_PressedToNormal_Start |  40.0 |  666.7 | 0.571428597F |
    // | PressedToNormal_End   | M_PressedToNormal_End   |  49.0 |  816.7 | 0.699999988F |
    // | PressedToHover_Start  | M_PressedToHover_Start  |  50.0 |  833.3 | 0.714285731F |
    // | PressedToHover_End    | M_PressedToHover_End    |  69.0 | 1150.0 | 0.985714257F |
    // -----------------------------------------------------------------------------------
    // _________________________________________________________
    // | Theme property |  Accessor  | Type  |  Default value  |
    // |________________|____________|_______|_________________|
    // | Foreground     | Foreground | Color | #FF000000 Black |
    // ---------------------------------------------------------
        class Controls_01_Checkmark
            : public winrt::implementation::Controls_01_CheckmarkT<Controls_01_Checkmark>
        {
            winrt::Windows::UI::Composition::CompositionPropertySet _themeProperties{ nullptr };
            winrt::Windows::UI::Color _themeForeground{ 0xFF, 0x00, 0x00, 0x00 };
            winrt::Windows::UI::Composition::CompositionPropertySet EnsureThemeProperties(winrt::Windows::UI::Composition::Compositor compositor);

            static winrt::Windows::Foundation::Numerics::float4 ColorAsVector4(winrt::Windows::UI::Color color);
        public:
            // Animation duration: 1.167 seconds.
            static constexpr int64_t c_durationTicks{ 11666666L };

            // Marker: NormalToHover_Start.
            static constexpr float M_NormalToHover_Start{ 0.0F };

            // Marker: NormalToHover_End.
            static constexpr float M_NormalToHover_End{ 0.128571436F };

            // Marker: NormalToPressed_Start.
            static constexpr float M_NormalToPressed_Start{ 0.142857149F };

            // Marker: NormalToPressed_End.
            static constexpr float M_NormalToPressed_End{ 0.271428585F };

            // Marker: HoverToNormal_Start.
            static constexpr float M_HoverToNormal_Start{ 0.285714298F };

            // Marker: HoverToNormal_End.
            static constexpr float M_HoverToNormal_End{ 0.414285719F };

            // Marker: HoverToPressed_Start.
            static constexpr float M_HoverToPressed_Start{ 0.428571433F };

            // Marker: HoverToPressed_End.
            static constexpr float M_HoverToPressed_End{ 0.557142854F };

            // Marker: PressedToNormal_Start.
            static constexpr float M_PressedToNormal_Start{ 0.571428597F };

            // Marker: PressedToNormal_End.
            static constexpr float M_PressedToNormal_End{ 0.699999988F };

            // Marker: PressedToHover_Start.
            static constexpr float M_PressedToHover_Start{ 0.714285731F };

            // Marker: PressedToHover_End.
            static constexpr float M_PressedToHover_End{ 0.985714257F };

            // Theme property: Foreground.
            static inline const winrt::Windows::UI::Color c_themeForeground{ 0xFF, 0x00, 0x00, 0x00 };


            winrt::Windows::UI::Color Foreground();
            void Foreground(winrt::Windows::UI::Color value);

            winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual TryCreateAnimatedVisual(
                winrt::Windows::UI::Composition::Compositor const& compositor,
                winrt::Windows::Foundation::IInspectable& diagnostics);

            // Converts a frame number to the corresponding progress value.
            double FrameToProgress(double frameNumber);

            // Returns a map from marker names to corresponding progress values.
            winrt::Windows::Foundation::Collections::IMapView<hstring, double> Markers();

            // Sets the color property with the given name, or does nothing if no such property
            // exists.
            void SetColorProperty(hstring const& propertyName, winrt::Windows::UI::Color value);

            // Sets the scalar property with the given name, or does nothing if no such property
            // exists.
            void SetScalarProperty(hstring const& propertyName, double value);
        };
